/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const PomodoroSession = IDL.Record({
  'startTime' : Time,
  'duration' : IDL.Nat,
  'endTime' : IDL.Opt(Time),
  'completed' : IDL.Bool,
});
export const StudyStreakRecord = IDL.Record({
  'date' : Time,
  'streakLength' : IDL.Nat,
});
export const SyllabusProgress = IDL.Record({
  'subject' : IDL.Text,
  'page' : IDL.Nat,
  'completed' : IDL.Bool,
  'chapter' : IDL.Text,
});
export const User = IDL.Record({ 'id' : IDL.Principal, 'username' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'completePomodoro' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'getPomodoroSessions' : IDL.Func([], [IDL.Vec(PomodoroSession)], ['query']),
  'getStudyStreaks' : IDL.Func([], [IDL.Vec(StudyStreakRecord)], ['query']),
  'getSyllabusProgress' : IDL.Func([], [IDL.Vec(SyllabusProgress)], ['query']),
  'getUser' : IDL.Func([], [User], []),
  'recordStudyStreak' : IDL.Func([IDL.Nat], [], []),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'startPomodoro' : IDL.Func([], [IDL.Nat], []),
  'updateSyllabusProgress' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const PomodoroSession = IDL.Record({
    'startTime' : Time,
    'duration' : IDL.Nat,
    'endTime' : IDL.Opt(Time),
    'completed' : IDL.Bool,
  });
  const StudyStreakRecord = IDL.Record({
    'date' : Time,
    'streakLength' : IDL.Nat,
  });
  const SyllabusProgress = IDL.Record({
    'subject' : IDL.Text,
    'page' : IDL.Nat,
    'completed' : IDL.Bool,
    'chapter' : IDL.Text,
  });
  const User = IDL.Record({ 'id' : IDL.Principal, 'username' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'completePomodoro' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'getPomodoroSessions' : IDL.Func([], [IDL.Vec(PomodoroSession)], ['query']),
    'getStudyStreaks' : IDL.Func([], [IDL.Vec(StudyStreakRecord)], ['query']),
    'getSyllabusProgress' : IDL.Func(
        [],
        [IDL.Vec(SyllabusProgress)],
        ['query'],
      ),
    'getUser' : IDL.Func([], [User], []),
    'recordStudyStreak' : IDL.Func([IDL.Nat], [], []),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'startPomodoro' : IDL.Func([], [IDL.Nat], []),
    'updateSyllabusProgress' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };